name: Flatter (GitHub Pages)

on:
  # Rebuild once a day
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:

jobs:
  flatter:
    name: Flatter
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/andyholmes/flatter/freedesktop:23.08
      options: --privileged

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      # See "GPG Signing" below
      - name: Setup GPG
        id: gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - run: |
          flatpak install -y --noninteractive org.electronjs.Electron2.BaseApp/x86_64/23.08
      - name: Build
        uses: MatthieuCoder/flatter@patch-1
        with:
          files: |
            flatpaks/com.ankama.Zaap/com.ankama.Zaap.yml
          gpg-sign: ${{ steps.gpg.outputs.fingerprint }}
          upload-pages-artifact: true
          upload-pages-includes: |
            CNAME

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: flatter
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4